import * as Print from "expo-print";
import * as Sharing from "expo-sharing";
import * as MailComposer from "expo-mail-composer";
import type { MonthGrid } from "./types";

/* Builds a clean, branded monthly prayer-timetable PDF on-device from the same
   data the app shows — no server round-trip, works offline. The one document is
   reused for Save/Share and Email so they always match what's on screen. */

const MONTHS = ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"];

function timetableHtml(grid: MonthGrid): string {
  const monthName = `${MONTHS[parseInt(grid.month.slice(5), 10) - 1]} ${grid.year}`;
  const rows = grid.days
    .map((d) => {
      const fri = d.weekday.startsWith("Fri");
      const day = parseInt(d.date.slice(8), 10);
      return `<tr class="${fri ? "fri" : ""}">
        <td class="day">${day} <span>${d.weekday.slice(0, 3)}</span></td>
        <td>${d.fajrBegins}<b>${d.fajrJamaah}</b></td>
        <td>${d.sunrise}</td>
        <td>${d.dhuhrBegins}<b>${d.dhuhrJamaah}</b></td>
        <td>${d.asrBegins}<b>${d.asrJamaah}</b></td>
        <td><b>${d.maghrib}</b></td>
        <td>${d.ishaBegins}<b>${d.ishaJamaah}</b></td>
      </tr>`;
    })
    .join("");

  return `<!doctype html><html><head><meta charset="utf-8"/><style>
    @page { margin: 26px 30px; }
    * { box-sizing: border-box; }
    body { font-family: -apple-system, "Helvetica Neue", Arial, sans-serif; color: #10241a; margin: 0; }
    .head { display: flex; align-items: center; justify-content: space-between; border-bottom: 3px solid #c9a227; padding-bottom: 12px; }
    .brand { font-size: 20px; font-weight: 800; color: #0e3d29; letter-spacing: -.3px; }
    .brand small { display:block; font-size: 11px; font-weight: 600; color: #6b7d72; letter-spacing: .5px; text-transform: uppercase; }
    .month { font-size: 22px; font-weight: 800; color: #c9a227; }
    table { width: 100%; border-collapse: collapse; margin-top: 14px; font-size: 10.5px; }
    thead th { background: #0e3d29; color: #f4efe2; font-size: 9px; text-transform: uppercase; letter-spacing: .6px; padding: 7px 4px; text-align: center; }
    thead th:first-child { text-align: left; padding-left: 8px; border-top-left-radius: 6px; }
    thead th:last-child { border-top-right-radius: 6px; }
    tbody td { padding: 5px 4px; text-align: center; border-bottom: 1px solid #e7e2d6; font-variant-numeric: tabular-nums; color: #6b7d72; }
    tbody td b { color: #10241a; margin-left: 4px; font-weight: 700; }
    td.day { text-align: left; padding-left: 8px; font-weight: 700; color: #10241a; }
    td.day span { color: #9aa89f; font-weight: 500; }
    tr.fri td { background: #faf5e2; }
    tr.fri td.day { color: #a9871d; }
    .legend { margin-top: 10px; font-size: 9px; color: #8a988e; }
    .foot { margin-top: 6px; font-size: 9px; color: #8a988e; text-align: center; }
  </style></head><body>
    <div class="head">
      <div class="brand">Kingston Mosque<small>Kingston Muslim Association</small></div>
      <div class="month">${monthName}</div>
    </div>
    <table>
      <thead><tr>
        <th>Date</th><th>Fajr</th><th>Sunrise</th><th>Dhuhr</th><th>ʿAsr</th><th>Maghrib</th><th>ʿIshā</th>
      </tr></thead>
      <tbody>${rows}</tbody>
    </table>
    <div class="legend">Each cell shows the <b>begins</b> time with the <b>jamāʿah (iqāmah)</b> time in bold. Maghrib is prayed at sunset. Fridays are highlighted.</div>
    <div class="foot">Generated by the Kingston Mosque app · kingstonmosque.org</div>
  </body></html>`;
}

/** Render the month to a PDF file and return its local uri. */
export async function makeTimetablePdf(grid: MonthGrid): Promise<string> {
  const { uri } = await Print.printToFileAsync({ html: timetableHtml(grid), base64: false });
  return uri;
}

/** Save / share the PDF via the native share sheet (AirDrop, Files, Mail, etc.). */
export async function shareTimetablePdf(grid: MonthGrid): Promise<void> {
  const uri = await makeTimetablePdf(grid);
  if (await Sharing.isAvailableAsync()) {
    await Sharing.shareAsync(uri, {
      mimeType: "application/pdf",
      dialogTitle: `Kingston Mosque — ${grid.month}`,
      UTI: "com.adobe.pdf",
    });
  }
}

/** Open the timetable directly in the OS print/save-to-PDF dialog. */
export async function printTimetable(grid: MonthGrid): Promise<void> {
  await Print.printAsync({ html: timetableHtml(grid) });
}

/** Email the PDF to the user via the native mail composer (they enter their
 *  own address). Returns false if no mail account is set up on the device. */
export async function emailTimetablePdf(grid: MonthGrid): Promise<boolean> {
  if (!(await MailComposer.isAvailableAsync())) return false;
  const uri = await makeTimetablePdf(grid);
  const monthName = `${MONTHS[parseInt(grid.month.slice(5), 10) - 1]} ${grid.year}`;
  await MailComposer.composeAsync({
    subject: `Kingston Mosque — Prayer Timetable, ${monthName}`,
    body: `As-salāmu ʿalaykum,\n\nAttached is the Kingston Mosque prayer timetable for ${monthName}.\n\nJazāk Allāhu khayran.`,
    attachments: [uri],
  });
  return true;
}
